pages:
  - name: ホーム - 未来
    path: /2023-05-05
  - name: ホーム - 現在
    path: /2023-04-28
  - name: ホーム - 過去
    path: /2023-04-20
  - name: 出走表
    path: /races/8a4ec73c-c008-4403-948b-c27258404c3d/race-card
  - name: オッズ - 締め切り前
    path: /races/9ea39d07-279c-46d4-8115-48b37c3a228a/odds
  - name: オッズ - 締め切り後
    path: races/dfa784f3-d0f9-493c-bd86-55bbdf27963b/odds
  - name: 結果
    path: /races/dfa784f3-d0f9-493c-bd86-55bbdf27963b/result
viewports:
  - name: Pixel 5
    width: 393
    height: 851
  - name: Kindle Fire HDX
    width: 800
    height: 1280
  - name: Desktop
    width: 1280
    height: 720
