name: Scoring
on:
  workflow_run:
    workflows:
      - Request
    types:
      - completed
env:
  TZ: "Asia/Tokyo"
  WSH_SCORING_DEBUG: "${{ secrets.WSH_SCORING_DEBUG }}"
  WSH_SCORING_TARGET_PATHS: "${{ secrets.WSH_SCORING_TARGET_PATHS }}"
jobs:
  payload:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      competition-status: ${{ steps.status.outputs.result }}
      result: ${{ steps.payload.outputs.result }}
    steps:
      - name: Download payload
        uses: dawidd6/action-download-artifact@575b1e4167df67acf7e692af784566618b23c71e # renovate: tag=v2.17.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: .github/workflows/request.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: payload.json
          path: /tmp
      - name: Read payload
        uses: actions/github-script@9ac08808f993958e9de277fe43a64532a609130e # renovate: tag=v6.0.0
        id: payload
        with:
          result-encoding: json
          script: |
            const payload = require('/tmp/payload.json');
            return payload;
      - name: Check competition status
        uses: actions/github-script@9ac08808f993958e9de277fe43a64532a609130e # renovate: tag=v6.0.0
        id: status
        with:
          result-encoding: string
          script: |
            return 'opened';
  initialize:
    runs-on: ubuntu-20.04
    steps:
      - name: POST /initialize -X POST -I
      - run: curl -sS ${{ TARGET_URL }}/api/initialize -X POST -I
  scoring:
    runs-on: ubuntu-20.04
    needs:
      - payload
      - initialize
    outputs:
      result: ${{ steps.scoring.outputs.export }}
    concurrency: scoring-${{ fromJSON(needs.payload.outputs.result).id }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: sudo apt-get install -y fonts-noto-cjk
      - name: Scoring
        id: scoring
        run: |
          yarn run scoring \
            --id ${TARGET_ID} \
            --url ${TARGET_URL}
        env:
          TARGET_ID: ${{ fromJSON(needs.payload.outputs.result).id }}
          TARGET_URL: ${{ fromJSON(needs.payload.outputs.result).url }}
  comment-payload:
    runs-on: ubuntu-20.04
    needs:
      - payload
    steps:
      - name: Competition is Closed Comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae # renovate: tag=v1.4.5
        if: needs.payload.outputs.competition-status != 'opened'
        with:
          comment-id: ${{ fromJSON(needs.payload.outputs.result).report_comment_id }}
          edit-mode: replace
          body: |
            :warning: **スコアを計測できませんでした**

            コンテスト開催前、もしくは、コンテストが終了しています

            ---

            :information_source: `/retry` とコメントすると、もう一度計測ができます
            :information_source: 登録内容を変更する場合は、issue を閉じて作り直してください
  comment-failure-scoring:
    runs-on: ubuntu-20.04
    needs:
      - payload
      - scoring
    if: always() && needs.scoring.result == 'failure'
    steps:
      - name: Comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae # renovate: tag=v1.4.5
        with:
          comment-id: ${{ fromJSON(needs.payload.outputs.result).report_comment_id }}
          edit-mode: replace
          body: |
            ## スコア

            :exclamation: **Lighthouse の計測ができませんでした**

            次を確認してください

            - URL が間違っていませんか
            - 計測対象のページは、誰でも閲覧できるようになっていますか
            - エラーページ以外では、ステータスコードが 200 で返却されますか

            ---

            Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            :information_source: `/retry` とコメントすると、もう一度計測ができます
            :information_source: 登録内容を変更する場合は、issue を閉じて作り直してください
  comment-scoring:
    runs-on: ubuntu-20.04
    needs:
      - payload
      - scoring
    steps:
      - name: Comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae # renovate: tag=v1.4.5
        with:
          comment-id: ${{ fromJSON(needs.payload.outputs.result).report_comment_id }}
          edit-mode: replace
          body: |
            ## スコア

            スコアは **${{ fromJSON(needs.scoring.outputs.result).result.score }}** です

            <details>
            <summary>buildInfo</summary>

            ```json
            ${{ toJSON(fromJSON(needs.scoring.outputs.result).buildInfo) }}
            ```

            </details>

            ---

            Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
